name: Build and Release VSynth

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qt6-base-dev portaudio19-dev libfftw3-dev cmake build-essential pkg-config
    
    - name: Clean and Build VSynth
      run: |
        chmod +x build.sh
        rm -rf build
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)
    
    - name: Create Linux package
      run: |
        mkdir -p vsynth-linux-x64
        cp build/vsynth vsynth-linux-x64/
        cp README.md vsynth-linux-x64/
        cp INSTALL.md vsynth-linux-x64/
        cp package/LICENSE.txt vsynth-linux-x64/
        tar -czf vsynth-linux-x64.tar.gz vsynth-linux-x64/
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsynth-linux-x64
        path: vsynth-linux-x64.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        brew install qt6 portaudio fftw cmake pkg-config
    
    - name: Build VSynth
      run: |
        rm -rf build
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(sysctl -n hw.ncpu)
    
    - name: Create macOS package
      run: |
        mkdir -p vsynth-macos
        cp build/vsynth vsynth-macos/
        cp README.md vsynth-macos/
        cp INSTALL.md vsynth-macos/
        cp package/LICENSE.txt vsynth-macos/
        tar -czf vsynth-macos.tar.gz vsynth-macos/
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsynth-macos
        path: vsynth-macos.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
    
    - name: Install PortAudio only
      run: |
        vcpkg install portaudio:x64-windows
    
    - name: Download and setup FFTW3
      run: |
        # Download precompiled FFTW3 for Windows
        Invoke-WebRequest -Uri "https://www.fftw.org/fftw-3.3.10-dll64.zip" -OutFile "fftw.zip"
        Expand-Archive -Path "fftw.zip" -DestinationPath "fftw"
        
        # Create lib files from def files
        lib /def:fftw/libfftw3f-3.def /out:fftw/libfftw3f-3.lib /machine:x64
        
        # Set environment variables
        echo "FFTW_ROOT=$env:GITHUB_WORKSPACE\fftw" >> $env:GITHUB_ENV
    
    - name: Build VSynth
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DFFTW_ROOT=$env:FFTW_ROOT
        cmake --build . --config Release
    
    - name: Create Windows package
      run: |
        mkdir vsynth-windows
        copy build\Release\vsynth.exe vsynth-windows\
        copy fftw\libfftw3f-3.dll vsynth-windows\
        copy README.md vsynth-windows\
        copy INSTALL.md vsynth-windows\
        copy package\LICENSE.txt vsynth-windows\
        tar -czf vsynth-windows.tar.gz vsynth-windows\
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsynth-windows
        path: vsynth-windows.tar.gz

  create-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vsynth-linux-x64/vsynth-linux-x64.tar.gz
          vsynth-macos/vsynth-macos.tar.gz
          vsynth-windows/vsynth-windows.tar.gz
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
